Feat/add juntos bot
he4rt/He4rt-Bot pull request #113
Opened 2021-09-26 20:39 UTC by HelenDias

## Infos

Comando `!juntos` que será utilizado para se inscrever no processo seletivo da Juntos Somos Mais (JS+).
O objetivo do comando é enviar algumas perguntas como mensagem privada ao usuário e, assim que ele responder todas, enviar essas perguntas em formato de card em um canal com o time da JS+. O time de people entrará em contato com as pessoas que aparecerem nesse canal.
Em caso de falha, será utilizado um Google Forms com as mesmas perguntas no lugar.

#### O que está sendo entregue?

- Adiciona o comando `!juntos` que chama o bot da JS+;
- Adiciona json com informações da JS+;
- Adicionar perguntas da JS+ no `assets/pt_BR.json`;
- Altera regra do `.eslint` para aceita `for` com `await` - isso é necessário para não ficar repetindo um monte de código, e tudo na lib do discord precisa ser `async`;

#### O que impacta?

Apenas esse novo comando.
Não deve interferir em nada já existente, pois nada foi refatorado ou alterado.

#### Plano de rollback

Reverter merge e usar Google Forms de backup durante o evento He4rt Conf 2021.

#### Evidências
![fluxo-inicial](https://user-images.githubusercontent.com/19653346/134823346-37d0a686-079b-45da-80ba-3bbbdb3e28d0.gif)
<img width="758" alt="Screen Shot 2021-09-26 at 17 37 43" src="https://user-images.githubusercontent.com/19653346/134823379-cbd6535e-ce53-46b5-9f55-ac803fbd8c4e.png">
<img width="762" alt="Screen Shot 2021-09-26 at 17 38 12" src="https://user-images.githubusercontent.com/19653346/134823386-927ef4e3-f96d-4aa3-b1ca-db288f39ede3.png">
<img width="761" alt="Screen Shot 2021-09-26 at 17 38 50" src="https://user-images.githubusercontent.com/19653346/134823413-3b2e5ed9-402c-4c68-afa5-45801a7b35e7.png">
<img width="761" alt="Screen Shot 2021-09-26 at 17 39 22" src="https://user-images.githubusercontent.com/19653346/134823424-77261f3c-7c97-438f-8255-35dbf5b089f2.png">

## Checklist

- [x] Código pronto
- [ ] Merge em `new-api`
- [ ] Merge em `master`
- [ ] Testes em produção

2021-09-27 22:25 UTC, kjkGustavo requested changes

2021-09-27 23:09 UTC, HelenDias commented on assets/pt_BR.json
> +	"responder": {
qual seria o ideal? `juntos`?

2021-09-28 17:11 UTC, kjkGustavo commented on assets/pt_BR.json
> +	"responder": {
Sim

2021-09-28 17:30 UTC, Xunjin commented on assets/pt_BR.json
> +	"responder": {
sim @HelenDias acredito que seria uma boa opção, o que acha @kjkGustavo ?

2021-09-28 20:47 UTC, HelenDias commented on assets/pt_BR.json
> +	"responder": {
feito: https://github.com/he4rt/He4rt-Bot/pull/113/commits/3e9c642f29978935873384247cef2bb910676a7b

2021-09-28 22:01 UTC, kjkGustavo approved these changes

2021-09-28 22:13 UTC, merged