Feat/add avatar command
he4rt/He4rt-Bot pull request #99
Opened 2020-12-22 19:51 UTC by PoorlyDefinedBehaviour

- Adiciona o comando `!avatar`

2020-12-22 20:03 UTC, kjkGustavo requested changes

2020-12-22 20:03 UTC, kjkGustavo commented on src/Commands/Mute.ts
> +      send("Você foi mutado, mais informações abaixo.", infoEmbed),
Aqui a mensagem deveria ser enviado na DM do usuário.

2020-12-22 20:40 UTC, PoorlyDefinedBehaviour commented on src/Commands/Mute.ts
> +      send("Você foi mutado, mais informações abaixo.", infoEmbed),
Feito

2020-12-22 20:40 UTC, PoorlyDefinedBehaviour commented
@kjkGustavo review

2020-12-23 17:21 UTC, kjkGustavo approved these changes

2020-12-23 17:21 UTC, merged